admin:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: app.swagger_ui
    # make a permanent redirection...
    permanent: true
    # ...and keep the original query string parameters
    keepQueryParams: true

api_login_check:
  path: /api/login_check

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
  path: /api/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }
